# Generated by Django 4.1 on 2022-08-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hungry_app', '0002_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='url',
            field=models.TextField(),
        ),
    ]
