# Generated by Django 4.1 on 2022-08-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hungry_app', '0003_alter_recipe_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.TextField(),
        ),
    ]
