# Generated by Django 4.1 on 2022-08-09 19:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hungry_app', '0004_alter_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='user',
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ManyToManyField(related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
